### ISSUE TITLE
add markdown linting

### ISSUE THREAD

**Issue by jmcampanini** [palantir-baseline/palantir-baseline.github.io#1]
can we add linters now? at the very least the markdown linter and hookup circleci to just run the tests...

**Comment by tomshen** [comment]
What do you mean by markdown linter?

**Comment by jmcampanini** [comment]
@zoubeiri found a linter: https://github.com/wooorm/remark-lint

**Comment by zoubeiri** [comment]
that's the one we're using for best-practices docs

**Comment by zoubeiri** [comment]
I added site building tests, I guess we can put in a linter too. There isn't too much text on the site though, not sure if it'll really add lift
